/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dir.h"
#include <string.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

readdir_res *
readdir_1(argp, clnt)
	nametype *argp;
	CLIENT *clnt;
{
	static readdir_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, READDIR, xdr_nametype, argp, xdr_readdir_res, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
