/*
 * msg_proc.c: implementation of the remote procedure "printmessage"
 */
#include <stdio.h>
#include <rpc/rpc.h> /* always needed */
#include "msg.h"     /* need this too: msg.h will be generated by rpcgen */

/*
 * Remote verson of "printmessage"
 */
int* printmessage_1_svc(char** msg, struct svc_req* sr)
{
    static int result;

    FILE* f;
    f = fopen("abc", "w");
    if (f == NULL)
    {
        result = 0;
        return (&result);
    }
    fprintf(f, "%s\n", *msg);
    fclose(f);
    result = 1;

    return (&result);
}
